//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputControls"",
    ""maps"": [
        {
            ""name"": ""TreeScene"",
            ""id"": ""8f8da3ac-774e-4a88-ba5b-729df90f816a"",
            ""actions"": [
                {
                    ""name"": ""Mouse"",
                    ""type"": ""Value"",
                    ""id"": ""c490dc66-cc12-4ba8-b521-28642b095b8c"",
                    ""expectedControlType"": ""Delta"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""23ae7bf4-73d7-4ccb-881d-5022af865fa7"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // TreeScene
        m_TreeScene = asset.FindActionMap("TreeScene", throwIfNotFound: true);
        m_TreeScene_Mouse = m_TreeScene.FindAction("Mouse", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // TreeScene
    private readonly InputActionMap m_TreeScene;
    private List<ITreeSceneActions> m_TreeSceneActionsCallbackInterfaces = new List<ITreeSceneActions>();
    private readonly InputAction m_TreeScene_Mouse;
    public struct TreeSceneActions
    {
        private @InputControls m_Wrapper;
        public TreeSceneActions(@InputControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Mouse => m_Wrapper.m_TreeScene_Mouse;
        public InputActionMap Get() { return m_Wrapper.m_TreeScene; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TreeSceneActions set) { return set.Get(); }
        public void AddCallbacks(ITreeSceneActions instance)
        {
            if (instance == null || m_Wrapper.m_TreeSceneActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TreeSceneActionsCallbackInterfaces.Add(instance);
            @Mouse.started += instance.OnMouse;
            @Mouse.performed += instance.OnMouse;
            @Mouse.canceled += instance.OnMouse;
        }

        private void UnregisterCallbacks(ITreeSceneActions instance)
        {
            @Mouse.started -= instance.OnMouse;
            @Mouse.performed -= instance.OnMouse;
            @Mouse.canceled -= instance.OnMouse;
        }

        public void RemoveCallbacks(ITreeSceneActions instance)
        {
            if (m_Wrapper.m_TreeSceneActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITreeSceneActions instance)
        {
            foreach (var item in m_Wrapper.m_TreeSceneActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TreeSceneActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TreeSceneActions @TreeScene => new TreeSceneActions(this);
    public interface ITreeSceneActions
    {
        void OnMouse(InputAction.CallbackContext context);
    }
}
